import Header from "@/components/Header";
import "./globals.css";
import clsx from "clsx";
import { Prosto_One, Commissioner } from "next/font/google";
import localFont from "next/font/local";

const primaryFont = Prosto_One({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--font-primary",
  fallback: ["cursive"],
});

const secondaryFont = localFont({
  variable: "--font-secondary",
  src: [
    {
      path: "../../public/fonts/sfprodisplayregular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/sfprodisplaymedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/sfprodisplaybold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

const alternateFont = Commissioner({
  subsets: ["cyrillic"],
  weight: "500",
  variable: "--font-alternate",
  fallback: ["sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={clsx(
          primaryFont.variable,
          secondaryFont.variable,
          alternateFont.variable,
          "font-primary"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
