import "./globals.css";
import clsx from "clsx";
import { Prosto_One } from "next/font/google";

const prostoOne = Prosto_One({
  subsets: ["cyrillic"],
  weight: "400",
  variable: "--font-prostoOne",
  fallback: ["cursive"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={clsx(prostoOne.variable, "font-body")}>{children}</body>
    </html>
  );
}
